version: "3.4"
services:
  database:
    build:
      context: ./samland-data
    image: sfugarino/mongodb
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - samland
  api:
    build:
      context: ./samland-api
    image: sfugarino/samland-api
    container_name: api
    ports:
      - "8080:8080"
    environment:
      - MONGODB_HOST=database
    depends_on:
      - database
    networks:
      - samland
  app:
    build:
      context: ./samland-app
    image: sfugarino/samland-app
    container_name: app
    ports:
      - "4200:80"
    environment:
      - SL_MUSIC_API_HOST=api
    depends_on:
      - api
    networks:
      - samland
networks:
  samland:
    driver: bridge
